"""Ready to update db table

Revision ID: 128851c88dac
Revises: 812eed4e9e18
Create Date: 2019-08-14 10:30:34.395801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128851c88dac'
down_revision = '812eed4e9e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AccountInfo', sa.Column('db_struct_update', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AccountInfo', 'db_struct_update')
    # ### end Alembic commands ###
