"""user table

Revision ID: 7a0fcd93e0f5
Revises: 
Create Date: 2019-05-15 10:13:59.565607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0fcd93e0f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserInfo_email'), 'UserInfo', ['email'], unique=True)
    op.create_index(op.f('ix_UserInfo_phone_number'), 'UserInfo', ['phone_number'], unique=True)
    op.create_index(op.f('ix_UserInfo_username'), 'UserInfo', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserInfo_username'), table_name='UserInfo')
    op.drop_index(op.f('ix_UserInfo_phone_number'), table_name='UserInfo')
    op.drop_index(op.f('ix_UserInfo_email'), table_name='UserInfo')
    op.drop_table('UserInfo')
    # ### end Alembic commands ###
