"""Update db table

Revision ID: 97c7c5af3e64
Revises: 128851c88dac
Create Date: 2019-08-14 10:34:49.713908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c7c5af3e64'
down_revision = '128851c88dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AccountInfo', 'db_struct_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AccountInfo', sa.Column('db_struct_update', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
